SELECT * FROM CITY

SELECT CITY, STATE FROM STATION

SELECT * FROM CITY WHERE ID = 1661

SELECT *
FROM CITY
WHERE COUNTRYCODE = "JPN"

SELECT name
FROM CITY
WHERE COUNTRYCODE = "JPN"

SELECT * 
FROM CITY 
WHERE POPULATION > 100000 AND COUNTRYCODE = "USA"

SELECT name
FROM CITY 
WHERE POPULATION > 120000 AND COUNTRYCODE = "USA"

SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID, 2) = 0
ORDER BY CITY

SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION

